spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /api
taco:
  order:
    pageSize: 10
logging:
  level:
    by: DEBUG