spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /api
  artemis:
    host: localhost
    port: 61617
    user: tacoweb
    password: 1234
taco:
  order:
    pageSize: 10
logging:
  level:
    by: DEBUG